version: '3'

networks:
  laravel:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_webserver
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
      - db

    networks:
      - laravel

  db:
    image: mysql:5.7.22
    container_name: mysql_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql


    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_service
    volumes:
      - './src:/var/www/html'
    ports:
      - "9000:9000"

    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis_service
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    networks:
      - laravel

  phpMyAdmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - laravel